.TH "check" 1 "November 1998" "Ztools 7.3.1"
.SH NAME
check \- integrity checker for infocom format story files
.SH SYNOPSIS
.B check
story-file
.RB "[ new-story-file ]"
.SH DESCRIPTION
.B Check
is a program for checking the integrity of Infocom format story files.
It can optionally generate a new story file by trimming the original
to the optimal length.
.SH OPTIONS
There are no command-line options for
.B check .
.LP
If a second argument is given,
it is treated as the name for the trimmed story file.
.SH SEE ALSO
.BR infodump (1),
.BR inforead (1),
.BR pix2gif (1),
.BR txd (1)
.SH AUTHOR
Mark Howell 7 August 1993 howell_ma@movies.enet.dec.com
.SH CURRENT MAINTAINER
Matthew Russotto russotto@pond.com
.