.TH "pix2gif" 1 "November 1998" "Ztools 7.3.1"
.SH NAME
pix2gif \- converts infocom MG1/EG1 picture files to separate GIF files
.SH SYNOPSIS
.B pix2gif
picture-file
.SH DESCRIPTION
.B Pix2gif
is a program extracting the individual images from an Infocom picture file.
Picture files only relate to V6 story files.
.SH OPTIONS
.B
pix2gif does not take any command-line options.
You must provide exactly one argument:
the name (or path) of an infocom format picture file.
.SH SEE ALSO
.BR check (1),
.BR infodump (1),
.BR inforead (1),
.BR txd (1)
.SH AUTHOR
Mark Howell 13 September 1992 howell_ma@movies.enet.dec.com
.SH CURRENT MAINTAINER
Matthew Russotto russotto@pond.com
.